import 'package:flutter/material.dart';

const kMainColor =Colors.teal;// Color(0xFFFFC12F);
const kSecondaryColor =Colors.black12;// Color(0xFFFFE6AC);
const kProductName = 'nameProd';
const kProductPrice = 'priceProd';
const kProductDescription = 'descriptionProd';
const kProductLocation = 'locationProd';
const kProductCategory = 'categoryProd';
const kProductsCollection = 'products';
const kUnActiveColor = Color(0xFFC1BDB8);
const kJackets = 'jackets';
const kTrousers = 'trousers';
const kTshirts = 't-shirts';
const kShoes = 'shoes';
const kOrders = 'Orders';
const kOrderDetails = 'OrderDetails';
const kTotallPrice = 'TotallPrice';
const kAddress = 'Address';
const kProductQuantity = 'quantityProd';
const kKeepMeLoggedIn = 'loginstate';
